const types = {
  SET_API_DETAILS: "SET_API_DETAILS",
  SET_BANNERS: "SET_BANNERS",
  SET_BLOGS: "SET_BLOGS",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_CONTESTS: "SET_CONTESTS",
  SET_COUPONS: "SET_COUPONS",
  SET_EVENTS: "SET_EVENTS",
  SET_FASHIONS: "SET_FASHIONS",
  SET_FEATURE_ITEMS: "SET_FEATURE_ITEMS",
  SET_HOURS: "SET_HOURS",
  SET_JOBS: "SET_JOBS",
  SET_LANDMARKS: "SET_LANDMARKS",
  SET_LOCALE: "SET_LOCALE",
  SET_MALL_DATA: "SET_MALL_DATA",
  SET_META_DATA: "SET_META_DATA",
  SET_POIS: "SET_POIS",
  SET_POPUPS: "SET_POPUPS",
  SET_PROMOTIONS: "SET_PROMOTIONS",
  SET_PROPERTY: "SET_PROPERTY",
  SET_REPOS: "SET_REPOS",
  SET_STORES: "SET_STORES",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS"
}

export default types